import {test} from 'node:test';import assert from 'node:assert/strict';import {session,isAllowed} from '../lib/access.mjs';import {admin,accountCookie} from '../lib/accounts.mjs';
const response=()=>({headers:{},status(n){this.statusCode=n;return this},json(x){this.body=x;return this},setHeader(k,v){this.headers[k]=v}});
test('school code plus approved account; disabled accounts lose existing session; teachers cannot administer',async()=>{
 const names=['SUPABASE_URL','SUPABASE_SERVICE_ROLE_KEY','SCHOOL_ACCESS_CODE','ADMIN_EMAILS'];const old=Object.fromEntries(names.map(n=>[n,process.env[n]]));const original=global.fetch;let approved=true;
 Object.assign(process.env,{SUPABASE_URL:'https://school.example',SUPABASE_SERVICE_ROLE_KEY:'server-secret',SCHOOL_ACCESS_CODE:'school-code',ADMIN_EMAILS:'admin@example.com'});
 global.fetch=async(url,options)=>{const body=url.includes('/token')?{access_token:'teacher-token',expires_in:3600}:{id:'teacher-id',email:'teacher@example.com',app_metadata:{school_id:'sevinc',role:'teacher',active:approved}};return {ok:true,status:200,json:async()=>body}};
 try{const wrong=response();await session({method:'POST',headers:{},body:{code:'bad',email:'teacher@example.com',password:'pass'}},wrong);assert.equal(wrong.statusCode,401);const login=response();await session({method:'POST',headers:{},body:{code:'2026',email:'teacher@example.com',password:'pass'}},login);assert.equal(login.statusCode,200);const req={method:'POST',headers:{cookie:login.headers['Set-Cookie'].split(';')[0]},body:{email:'new@example.com',password:'long-password'}};assert.equal(await isAllowed(req),true);const forbidden=response();await admin(req,forbidden);assert.equal(forbidden.statusCode,403);assert.equal(await isAllowed({headers:{cookie:'school_account=teacher-token'}}),false);approved=false;assert.equal(await isAllowed(req),false);const refused=response();await session({method:'POST',headers:{},body:{code:'2026',email:'teacher@example.com',password:'pass'}},refused);assert.equal(refused.statusCode,403)}finally{global.fetch=original;for(const n of names){if(old[n]===undefined)delete process.env[n];else process.env[n]=old[n]}}
});
test('only administrator can create approved teachers and cannot disable own account',async()=>{const names=['SUPABASE_URL','SUPABASE_SERVICE_ROLE_KEY','SCHOOL_ACCESS_CODE','ADMIN_EMAILS'];const old=Object.fromEntries(names.map(n=>[n,process.env[n]]));const original=global.fetch;Object.assign(process.env,{SUPABASE_URL:'https://school.example',SUPABASE_SERVICE_ROLE_KEY:'secret',SCHOOL_ACCESS_CODE:'code',ADMIN_EMAILS:'admin@example.com'});let created;global.fetch=async(url,options)=>{let body={id:'admin-id',email:'admin@example.com',app_metadata:{}};if(url.endsWith('/admin/users')&&options.method==='POST'){created=JSON.parse(options.body);body={id:'new-id'}}return {ok:true,status:200,json:async()=>body}};try{const req={method:'POST',headers:{cookie:'school_account='+accountCookie('admin-token')},body:{email:'teacher@example.com',password:'twelvecharacters'}};const r=response();await admin(req,r);assert.equal(r.statusCode,201);assert.deepEqual(created.app_metadata,{school_id:'sevinc',role:'teacher',active:true});const deny=response();await admin({...req,method:'PATCH',body:{id:'admin-id',active:false}},deny);assert.equal(deny.statusCode,403)}finally{global.fetch=original;for(const n of names){if(old[n]===undefined)delete process.env[n];else process.env[n]=old[n]}}});
