import {sessionSecret} from './school.mjs';
import {createHmac,timingSafeEqual} from 'node:crypto';
const signature=value=>createHmac('sha256',sessionSecret).update(value).digest('base64url');
export function accountCookie(token){const value=Buffer.from(token).toString('base64url');return value+'.'+signature(value)}
export const accountMode=()=>!!(process.env.SUPABASE_URL||process.env.SUPABASE_SERVICE_ROLE_KEY);
const school=()=>process.env.SCHOOL_ID||'sevinc';
export function role(user){if(!user)return null;const admins=(process.env.ADMIN_EMAILS||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);if(admins.includes(user.email?.toLowerCase()))return 'admin';const m=user.app_metadata;return m?.school_id===school()&&m?.role==='teacher'&&m?.active===true?'teacher':null}
export async function authRequest(path,{method='GET',body,token}={}){if(!process.env.SUPABASE_URL||!process.env.SUPABASE_SERVICE_ROLE_KEY)throw Error('Hesap girişi henüz yönetici tarafından yapılandırılmadı.');const r=await fetch(process.env.SUPABASE_URL.replace(/\/$/,'')+'/auth/v1'+path,{method,headers:{apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,Authorization:'Bearer '+(token||process.env.SUPABASE_SERVICE_ROLE_KEY),'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Hesap işlemi tamamlanamadı. Bilgileri ve hesap erişimini kontrol edin.');return r.status===204?{}:r.json()}
export async function currentUser(req){const raw=String(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('school_account='))?.slice(15);if(!raw)return null;try{const cookie=decodeURIComponent(raw),split=cookie.lastIndexOf('.'),value=cookie.slice(0,split),sig=Buffer.from(cookie.slice(split+1)),expected=Buffer.from(signature(value));if(split<1||sig.length!==expected.length||!timingSafeEqual(sig,expected))return null;const user=await authRequest('/user',{token:Buffer.from(value,'base64url').toString('utf8')});return role(user)?user:null}catch{return null}}
export async function admin(req,res){res.setHeader('Cache-Control','no-store');const {sameOrigin}=await import('./access.mjs');if(!sameOrigin(req))return res.status(403).json({error:'İstek kaynağı uygun değil.'});const user=await currentUser(req);if(role(user)!=='admin')return res.status(403).json({error:'Yönetici yetkisi gerekiyor.'});try{if(req.method==='GET'){const page=Math.max(1,Math.min(1000,Number(req.query?.page||new URL(req.url,'http://local').searchParams.get('page')||1)));const data=await authRequest('/admin/users?page='+page+'&per_page=50');return res.status(200).json({page,users:(data.users||[]).filter(u=>role(u)==='teacher'||u.app_metadata?.school_id===school()).map(u=>({id:u.id,email:u.email,active:u.app_metadata?.active===true}))})}if(req.method==='POST'){const {email,password}=req.body||{};if(typeof email!=='string'||!/^\S+@\S+\.\S+$/.test(email)||email.length>254||typeof password!=='string'||password.length<12||password.length>128)return res.status(400).json({error:'Geçerli e-posta ve en az 12 karakterli şifre girin.'});const created=await authRequest('/admin/users',{method:'POST',body:{email:email.trim(),password,email_confirm:true,app_metadata:{school_id:school(),role:'teacher',active:true}}});return res.status(201).json({ok:true,id:created.id})}if(req.method==='PATCH'){const {id,active}=req.body||{};if(typeof id!=='string'||!/^[-a-zA-Z0-9]+$/.test(id)||typeof active!=='boolean')return res.status(400).json({error:'Hesap seçimi geçersiz.'});const target=await authRequest('/admin/users/'+id);if(role(target)==='admin'||target.app_metadata?.school_id!==school())return res.status(403).json({error:'Bu hesap değiştirilemez.'});await authRequest('/admin/users/'+id,{method:'PUT',body:{app_metadata:{...target.app_metadata,active}}});return res.status(200).json({ok:true})}return res.status(405).json({error:'İstek yöntemi uygun değil.'})}catch(e){return res.status(400).json({error:e.message})}}
