import {randomUUID} from 'node:crypto';import {profileUser,database,usage,profileMode} from '../lib/profiles.mjs';import {billingReady,iyzico,validPlan,syncSubscription} from '../lib/billing.mjs';import {sameOrigin} from '../lib/access.mjs';
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(!sameOrigin(req))return res.status(403).json({error:'İstek kaynağı uygun değil.'});try{if(!profileMode())return res.status(503).json({error:'Kişisel hesaplar ve planlar henüz etkinleştirilmedi. Mevcut okul koduyla test hazırlamaya devam edebilirsiniz.'});const p=await profileUser(req);if(!p)return res.status(401).json({error:'Kişisel hesabınızla giriş yapın.'});const action=req.query?.action||new URL(req.url,'http://local').searchParams.get('action');if(req.method==='GET'&&action==='form'){const id=req.query?.checkout||new URL(req.url,'http://local').searchParams.get('checkout');if(!/^[a-f0-9-]{36}$/.test(id))throw Error('Ödeme formu bulunamadı.');const [c]=await database('billing_checkouts?id=eq.'+id+'&account_id=eq.'+p.id+'&select=*');if(!c||new Date(c.expires_at)<new Date())throw Error('Ödeme formunun süresi doldu.');res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('X-Frame-Options','DENY');return res.status(200).send('<!doctype html><html lang="tr"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sevinç Plus · Kart ödemesi</title><body><h1>Sevinç Plus — 50 TL / ay</h1><p>'+ (process.env.IYZICO_BASE_URL==='https://sandbox-api.iyzipay.com'?'TEST ÖDEME ORTAMI — gerçek ödeme alınmaz. ':'') + 'Her ay otomatik yenilenir. Aboneliğini panelde iptal edebilirsin.</p><div id="iyzipay-checkout-form" class="responsive"></div>'+c.form_html+'</body></html>')}
 if(req.method==='GET'){if(p.subscription_ref&&billingReady()){const subscription=await syncSubscription(p.subscription_ref);const [fresh]=await database('teacher_profiles?id=eq.'+p.id+'&select=*');return res.status(200).json({configured:billingReady(),subscriptionStatus:subscription.subscriptionStatus,sandbox:process.env.IYZICO_BASE_URL==='https://sandbox-api.iyzipay.com',...await usage(fresh)})}return res.status(200).json({configured:billingReady(),sandbox:process.env.IYZICO_BASE_URL==='https://sandbox-api.iyzipay.com',...await usage(p)})}
 if(req.method!=='POST')return res.status(405).json({error:'İstek yöntemi uygun değil.'});const b=req.body||{};
 if(b.action==='cancel'){if(!p.subscription_ref)throw Error('Aktif abonelik yok.');await iyzico('/v2/subscription/subscriptions/'+encodeURIComponent(p.subscription_ref)+'/cancel','POST',{});await syncSubscription(p.subscription_ref);return res.status(200).json({ok:true,message:'Otomatik yenileme iptal edildi. Ödenmiş dönemin sonuna kadar Plus erişimi sürer.'})}
 if(p.subscription_ref){const current=await syncSubscription(p.subscription_ref);if(current.subscriptionStatus==='ACTIVE'||current.paidUntil)throw Error('Mevcut aboneliğiniz var. Yeni abonelik açılmaz.')}
 const plan=await iyzico('/v2/subscription/pricing-plans/'+encodeURIComponent(process.env.IYZICO_PLAN_REFERENCE||''));if(!validPlan(plan.data))throw Error('Ödeme planı 50 TL/ay olarak doğrulanamadı. Yönetici planı düzeltmeli.');
 const fields=['name','surname','email','gsmNumber','identityNumber','address','city'];if(!fields.every(k=>typeof b[k]==='string'&&b[k].trim().length>0&&b[k].length<500)||!/^\S+@\S+\.\S+$/.test(b.email)||!/^\d{11}$/.test(b.identityNumber)||!/^\+90\d{10}$/.test(b.gsmNumber))return res.status(400).json({error:'Fatura bilgilerini doldurun. Telefon +90 ile, kimlik numarası 11 haneli olmalı.'});if(b.consent!==true)throw Error('Aylık yenileme koşulunu onaylayın.');const origin=new URL(process.env.APP_URL);if(origin.protocol!=='https:')throw Error('Ödeme için HTTPS yayın adresi gerekiyor.');const id=randomUUID();const reserved=await database('rpc/reserve_checkout',{method:'POST',body:{p_account:p.id,p_id:id}});if(reserved.existing)return res.status(200).json({url:'/api/billing?action=form&checkout='+reserved.id});const customer={name:b.name.trim(),surname:b.surname.trim(),email:b.email.trim(),gsmNumber:b.gsmNumber,identityNumber:b.identityNumber,billingAddress:{address:b.address.trim(),contactName:b.name+' '+b.surname,city:b.city.trim(),country:'Türkiye'}};
 const result=await iyzico('/v2/subscription/checkoutform/initialize','POST',{locale:'tr',conversationId:id,callbackUrl:origin.origin+'/api/payment-callback?checkout='+id,pricingPlanReferenceCode:process.env.IYZICO_PLAN_REFERENCE,subscriptionInitialStatus:'ACTIVE',customer});if(!result.token||typeof result.checkoutFormContent!=='string')throw Error('Ödeme formu oluşturulamadı.');await database('billing_checkouts?id=eq.'+id,{method:'PATCH',body:{token:result.token,form_html:result.checkoutFormContent,expires_at:new Date(Date.now()+Math.max(60,Math.min(Number(result.tokenExpireTime)||1800,86400))*1000).toISOString()}});return res.status(200).json({url:'/api/billing?action=form&checkout='+id});
 }catch(e){return res.status(503).json({error:e.message})}}
