import {profileUser,createProfile,profileCookie,database,hashCode,usage,profilesReady} from '../lib/profiles.mjs';
import {sameOrigin} from '../lib/access.mjs';import {schoolCode} from '../lib/school.mjs';
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(!sameOrigin(req))return res.status(403).json({error:'İstek kaynağı uygun değil.'});try{
 if(req.method==='GET'){const p=await profileUser(req);return res.status(200).json({configured:profilesReady(),authenticated:!!p,...(p?await usage(p):{})})}
 if(req.method==='DELETE'){res.setHeader('Set-Cookie','teacher_profile=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0');return res.status(200).json({ok:true})}
 if(req.method!=='POST')return res.status(405).json({error:'İstek yöntemi uygun değil.'});const b=req.body||{};if(!profilesReady())throw Error('Kişisel hesap sistemi henüz etkinleştirilmedi.');const ip=String(req.headers['x-forwarded-for']||req.socket?.remoteAddress||'unknown').split(',')[0];const permit=await database('rpc/allow_account_attempt',{method:'POST',body:{p_ip:hashCode('ip:'+ip)}});if(!permit)return res.status(429).json({error:'Çok fazla giriş denemesi. 15 dakika sonra tekrar deneyin.'});if(b.schoolCode!==schoolCode)return res.status(401).json({error:'Okul kodu doğru değil.'});
 if(b.action==='register'){const name=String(b.name||'').trim();if(name.length<2||name.length>80)return res.status(400).json({error:'2–80 karakterli bir isim girin.'});const {profile,code}=await createProfile(name);res.setHeader('Set-Cookie',profileCookie(profile.id));return res.status(201).json({ok:true,code,name})}
 const code=String(b.accountCode||'').replace(/\s|-/g,'');if(!/^\d{12}$/.test(code))return res.status(401).json({error:'12 haneli kişisel hesap kodunu girin.'});const [p]=await database('teacher_profiles?code_hash=eq.'+hashCode(code)+'&select=*');if(!p?.active)return res.status(401).json({error:'Hesap kodu yanlış veya hesabın erişimi kapalı.'});res.setHeader('Set-Cookie',profileCookie(p.id));return res.status(200).json({ok:true})
 }catch(e){return res.status(503).json({error:e.message})}}
